---
mysql:                  #Info on connecting to the sql server.
  username: username
  password: password
  hostname: hostname
  database: database
user_id: 0              #used in non-faction requests, like !player, and !vault
version: 2.18.0         #the tyrant version
user_agent: 'Clementine IRC Bot. Source: http://github.com/catepillar/tyrant-clementine'
bot:                    #Irc bot configuration
  name: botname
  password: password
  server: irc.mibbit.net
plugins:                #the plugins and options associated with them
  PlayerInfo:
    admins:
    - name1
    - name2
  FactionInfo: {}
  Vault: {}
channels:               #Channels to join on start. Channels need quotes because of the "#" sign
- "#channel1"
- "#channel1"
